#!/bin/bash

: ${RPI_XC_IMAGE:=stephenthirlwall/rpi-xc}

# Raspbian 32-bit
BIN_PREFIX=arm-linux-gnueabihf
BIN_DIR=gcc-linaro-$BIN_PREFIX-raspbian

## Raspbian 64-bit
#BIN_PREFIX=arm-linux-gnueabihf
#BIN_DIR=gcc-linaro-$BIN_PREFIX-raspbian-x64
#
## Software-float GNU (not sure what this is really)
#BIN_PREFIX=arm-bcm2708-linux-gnueabi
#BIN_DIR=$BIN_PREFIX
#
## Hardware-float GNU (not sure what this is really)
#BIN_PREFIX=arm-bcm2708hardfp-linux-gnueabi
#BIN_DIR=$BIN_PREFIX

CCPREFIX=/rpi/arm-bcm2708/$BIN_DIR/bin/$BIN_PREFIX-

# If we are not running via boot2docker
if [ -z $DOCKER_HOST ]; then
    USER_IDS="-e BUILDER_UID=$( id -u ) -e BUILDER_GID=$( id -g )"
fi

docker run -i --rm \
    -v $PWD:/build \
    -e CCPREFIX=$CCPREFIX \
    $USER_IDS \
    $RPI_XC_IMAGE "$@"
