#!/bin/bash

# Load up the config file if it exists
: ${RPXC_CONFIG:=~/.rpxc}

[[ -f "$RPXC_CONFIG" ]] && source "$RPXC_CONFIG"

# Set the docker image
: ${RPXC_IMAGE:=sdt4docker/raspberry-pi-cross-compiler}

#------------------------------------------------------------------------------
# Helpers
#
err() {
    echo -e >&2 ERROR: $@\\n
}

has() {
    # eg. has command update
    local kind=$1
    local name=$2

    type -t $kind:$name | grep -q function
}

#------------------------------------------------------------------------------
# Command handlers
#
command:update-image() {
    docker pull $RPXC_IMAGE
}

help:update-image() {
    echo Pull the latest $RPXC_IMAGE .
}

command:update-script() {
    if cmp -s <( docker run $RPXC_IMAGE ) $0; then
        echo $0 is up to date
    else
        echo -n Updating $0 '... '
        docker run $RPXC_IMAGE > $0 && echo ok
    fi
}

help:update-image() {
    echo Update $0 from $RPXC_IMAGE .
}

command:update() {
    command:update-image
    command:update-script
}

help:update() {
    echo Pull the latest $RPXC_IMAGE, and then update $0 from that.
}

command:help() {
    if [[ $# != 0 ]]; then
        if ! has command $1; then
            err \"$1\" is not an rpxc command
            command:help
        elif ! has help $1; then
            err No help found for \"$1\"
        else
            help:$1
        fi
    else
        cat >&2 <<ENDHELP
usage: rpxc command [args]

By default, runs the given command in an rpxc container.

Builtin commands:
    update-image
    update-script
    update

For command help use: $0 help <command>
ENDHELP
    fi
}

#------------------------------------------------------------------------------
# Command-line processing
#
if [[ $# == 0 ]]; then
    command:help
    exit
fi

case $1 in

    --)
        # Everything after this is the command-line to be executed
        shift
        ;;

    -*)
        # Option processing would go here
        command:help
        exit
        ;;

    *)
        # If this is a builtin command, execute it, otherwise fall through
        if has command $1; then
            command:$1 "${@:2}" # array slice skipping first element
            exit $?
        fi
        ;;

esac

# Choose one of raspbian32, raspbian64, gnusw, gnuhw
: ${RPXC_TARGET:=raspbian32}

case $RPXC_TARGET in

    raspbian32)
        # Raspbian 32-bit
        BIN_PREFIX=arm-linux-gnueabihf
        BIN_DIR=gcc-linaro-$BIN_PREFIX-raspbian
        ;;

    raspbian64)
        # Raspbian 64-bit
        BIN_PREFIX=arm-linux-gnueabihf
        BIN_DIR=gcc-linaro-$BIN_PREFIX-raspbian-x64
        ;;

    gnusw)
        # Software-float GNU (not sure what this is really)
        BIN_PREFIX=arm-bcm2708-linux-gnueabi
        BIN_DIR=$BIN_PREFIX
        ;;

    gnuhw)
        # Hardware-float GNU (not sure what this is really)
        BIN_PREFIX=arm-bcm2708hardfp-linux-gnueabi
        BIN_DIR=$BIN_PREFIX
        ;;

    *)
        err Unknown RPXC_TARGET=$RPXC_TARGET \
            "\n"Possible values: raspbian32, raspbian64, gnusw, gnuhw
        ;;

esac

CROSS_COMPILE=/rpxc/arm-bcm2708/$BIN_DIR/bin/$BIN_PREFIX-

# If we are not running via boot2docker
if [ -z $DOCKER_HOST ]; then
    USER_IDS="-e BUILDER_UID=$( id -u ) -e BUILDER_GID=$( id -g )"
fi

docker run -i -t --rm \
    -v $PWD:/build \
    -e ARCH=arm \
    -e CROSS_COMPILE=$CROSS_COMPILE \
    $USER_IDS \
    $RPXC_ARGS \
    $RPXC_IMAGE "$@"

################################################################################
#
#   This image is not intended to be run manually.
#
#   To install the rpxc helper, run the following commands:
#
#       docker run sdt4docker/raspberry-pi-cross-compiler > rpxc
#       chmod +x rpxc
#
#   You may then wish to move rpxc to somewhere in your path.
#
################################################################################
